#!/bin/bash

echo "MALE Webcrawler SSL v2.0" >&2
echo "USO: ./executeme <url> <profundidade>" >&2
echo "OU : ./testeme <url> <profundidade>" >&2
echo "Download dos arquivos na pasta male_webcrawler/" >&2
argumentos=0;
if [ "$#" == 0 ]; then
      echo "" >&2
      echo "Ajuda" >&2
      echo "Repositorio GIT: https://github.com/mariosaldanha/trabalho_redes_ssl" >&2
      echo "" >&2
      echo "-h : esta ajuda" >&2
      echo "-c : compila binario" >&2
      echo "-i : instala bibliotecas necessarias para compilacao" >&2
      echo "make clean: exclui os arquivos de saida do webcrawler" >&2
else
while getopts ":hci" opt; do
  case $opt in
    h)
      echo "" >&2
      echo "Ajuda" >&2
      echo "MALE Webcrawler v2.0" >&2
      echo "Repositorio GIT: https://github.com/mariosaldanha/trabalho_redes_ssl" >&2
      echo "-h : esta ajuda" >&2
      echo "-c : compila binario" >&2
      echo "-i : instala bibliotecas necessarias para compilacao" >&2
      echo "make clean: exclui os arquivos de saida do webcrawler" >&2
      ;;
    c)
      echo "Compilar webcrawler" >&2
      make
      ;;
    i)
      echo "Instalar bibliotecas necessarias pra compilacao" >&2
      sudo apt-get install libboost-regex-dev
      sudo apt-get install libssl-dev      
      ;;
    \?)
      echo "Opcao invalida: -$OPTARG" >&2
      ;;
  esac
argumentos=1;
done
if [ $# = 2 ]; then
	if [ $argumentos = 0 ]; then
		./testeme $1 $2
	fi
fi

fi
